

# app.yaml
runtime: python313

env_variables:
  SECRET_KEY: "your-secret-key-here-change-this-in-production"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 10